<?xml version="1.0" encoding="utf-8"?>
<Project>

  <!-- Empty target so that `dotnet test` will work on the solution -->
  <!-- https://github.com/Microsoft/vstest/issues/411 -->
  <Target Name="VSTest" Condition="'$(IsTestProject)' == 'true'"/>

  <ItemGroup>
    <!-- Shared config files that have to exist at root level. -->
    <SixLaborsConfigFilesToCopy Include="$(MSBuildThisFileDirectory)..\..\.editorconfig" />
    <SixLaborsConfigFilesToCopy Include="$(MSBuildThisFileDirectory)..\..\.gitattributes" />
    <SixLaborsConfigFilesToCopy Include="$(MSBuildThisFileDirectory)..\..\codecov.yml" />
    <SixLaborsConfigFilesToCopy Include="$(MSBuildThisFileDirectory)..\..\global.json" />
  </ItemGroup>

  <!-- Copy the config files on src build. -->
  <Target Name="SixLaborsCopyConfigFiles" BeforeTargets="Build" Condition="'$(SIXLABORS_DISABLE_CONFIG_COPY)' == ''">
    <Copy SourceFiles="@(SixLaborsConfigFilesToCopy)"
          SkipUnchangedFiles = "true"
          DestinationFolder="$(SixLaborsSolutionDirectory)" />
  </Target>

  <!--
      This target is responsible for copying licensing files to the licensing NuGet package
      to our build output.
      See SixLabors.Src.props for the package references.
      Hook into NuGet pack.
  -->
  <PropertyGroup>
    <TargetsForTfmSpecificContentInPackage>
      $(TargetsForTfmSpecificContentInPackage);_SixLabors_AddLicensingFiles
    </TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

</Project>
